apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
        - name: PROJECT
          image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
          ports:
            - containerPort: PORT_CONTAINER

          env:
            - name: SECRET_KEY_YANDEX
              valueFrom:
                secretKeyRef:
                  name: file-storage-production-config-secret
                  key: SECRET_KEY_YANDEX
            - name: ACCESS_KEY_YANDEX
              valueFrom:
                secretKeyRef:
                  name: file-storage-production-config-secret
                  key: ACCESS_KEY_YANDEX
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: file-storage-production-config-secret
                  key: MONGODB_URL
            - name: ENV_TYPE
              valueFrom:
                secretKeyRef:
                  name: file-storage-production-config-secret
                  key: ENV_TYPE
            - name: STORAGE_POST_SERVICE
              valueFrom:
                secretKeyRef:
                  name: file-storage-production-config-secret
                  key: STORAGE_POST_SERVICE
            - name: PORT_TCP
              valueFrom:
                secretKeyRef:
                  name: file-storage-production-config-secret
                  key: PORT_TCP
