apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
        - name: PROJECT
          image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
          ports:
            - containerPort: PORT_CONTAINER
          env:
            - name: ENV_TYPE
              valueFrom:
                secretKeyRef:
                  name: photer-gateway-api-production-config-secret
                  key: ENV_TYPE
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: photer-gateway-api-production-config-secret
                  key: EMAIL_HOST
            - name: EMAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: photer-gateway-api-production-config-secret
                  key: EMAIL_PORT
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: photer-gateway-api-production-config-secret
                  key: EMAIL_USER
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: photer-gateway-api-production-config-secret
                  key: EMAIL_PASSWORD
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: photer-gateway-api-production-config-secret
                  key: BASE_URL
            - name: CAPTCHA_SECRET
              valueFrom:
                secretKeyRef:
                  name: photer-gateway-api-production-config-secret
                  key: CAPTCHA_SECRET
            - name: GITHUB_CLIENT
              valueFrom:
                secretKeyRef:
                  name: photer-gateway-api-production-config-secret
                  key: GITHUB_CLIENT
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: photer-gateway-api-production-config-secret
                  key: GITHUB_CLIENT_SECRET
            - name: GOOGLE_CLIENT
              valueFrom:
                secretKeyRef:
                  name: photer-gateway-api-production-config-secret
                  key: GOOGLE_CLIENT
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: photer-gateway-api-production-config-secret
                  key: GOOGLE_CLIENT_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: photer-gateway-api-production-config-secret
                  key: JWT_SECRET
            - name: JWT_ACCESS_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: photer-gateway-api-production-config-secret
                  key: JWT_ACCESS_EXPIRATION_TIME
            - name: JWT_REFRESH_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: photer-gateway-api-production-config-secret
                  key: JWT_REFRESH_EXPIRATION_TIME
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: photer-gateway-api-production-config-secret
                  key: DATABASE_URL